export const POSTS = [
  {
    _id: "1",
    text: "Here's Zinedine Zidane after winning 3 UEFA Champions Leagues!! 😍",
    img: "/posts/post1.png",
    user: {
      username: "adityans",
      profileImage: "/avatars/boy1.png",
      fullName: "Aditya Narayan Sahoo",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "alinasahoo",
          profileImage: "/avatars/girl1.png",
          fullName: "Alina Sahoo",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "You seem like a chill guy 😊",
    user: {
      username: "adityans",
      profileImage: "/avatars/boy2.png",
      fullName: "Aditya Narayan Sahoo",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "alinasahoo",
          profileImage: "/avatars/girl2.png",
          fullName: "Alina Sahoo",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
    img: "/posts/post2.png",
    user: {
      username: "adityans",
      profileImage: "/avatars/boy3.png",
      fullName: "Aditya Narayan Sahoo",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "I'm learning GO this week. Any tips? 🤔",
    img: "/posts/post3.png",
    user: {
      username: "adityans",
      profileImage: "/avatars/boy3.png",
      fullName: "Aditya Narayan Sahoo",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "alinasahoo",
          profileImage: "/avatars/girl3.png",
          fullName: "Alina Sahoo",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "Aditya Narayan Sahoo",
    username: "adityans",
    profileImage: "/avatars/boy2.png",
  },
  {
    _id: "2",
    fullName: "Alina Sahoo",
    username: "alinasahoo",
    profileImage: "/avatars/girl1.png",
  },
  {
    _id: "3",
    fullName: "Indramani Sahoo",
    username: "indramanisahoo",
    profileImage: "/avatars/boy3.png",
  },
  {
    _id: "4",
    fullName: "Lilabati Sahoo",
    username: "lilabatisahoo",
    profileImage: "/avatars/girl2.png",
  },
];
